export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const HANDLE_EDIT = "HANDLE_EDIT";
export const HANDLE_UPDATE = "HANDLE_UPDATE";
export const HANDLE_DELETE = "HANDLE_DELETE";
export const HANDLE_STATUS = "HANDLE_STATUS";
